apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APPLICATION
  namespace: $NAMESPEACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APPLICATION
  template:
    metadata:
      labels:
        app: $APPLICATION
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: $APPLICATION
          image: $IMAGE_NAME
          ports:
            - containerPort: 8080
              name: $APPLICATION
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: $APPLICATION
spec:
  type: NodePort
  selector:
    app: $APPLICATION
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web

